/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clicker01;

import static clicker01.server.database;
import static clicker01.server.password;
import static clicker01.server.username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


/**
 *
 * @author Vues
 */
public class hsForm extends javax.swing.JFrame {

    /**
     * Creates new form hsForm
     */
    
    public void fillScores() throws SQLException{
        try{
            Connection con = DriverManager.getConnection(database,username,password);
            String sql = "SELECT * FROM bestclicker ORDER BY score DESC LIMIT 1";
            String sql2 = "SELECT * FROM bestclicker order by score DESC OFFSET 1 LIMIT 1";
            String sql3 = "SELECT * FROM bestclicker order by score DESC OFFSET 2 LIMIT 1";

            Statement pStatement = con.createStatement();
            Statement pStatement1 = con.createStatement();
            Statement pStatement2 = con.createStatement();
            
            ResultSet rs = pStatement.executeQuery(sql);
            ResultSet rs1 = pStatement1.executeQuery(sql2);
            ResultSet rs2 = pStatement2.executeQuery(sql3);

            while(rs.next()){
                p1ScoreTextField.setText(String.valueOf(rs.getInt("score")));
                p1NameTextField.setText(rs.getString("name"));
            }
            
            while(rs1.next()){
                p2ScoreTextField.setText(String.valueOf(rs1.getInt("score")));
                p2NameTextField.setText(rs1.getString("name"));
            }
            
            while(rs2.next()){
                p3ScoreTextField.setText(String.valueOf(rs2.getInt("score")));
                p3NameTextField.setText(rs2.getString("name"));
            }                      
            
            rs.close();
            con.close();
            pStatement.close();
        }catch(Exception e){
            
        }
    }

    
    public hsForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        p1NameTextField = new javax.swing.JTextField();
        p1ScoreTextField = new javax.swing.JTextField();
        playersLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        p2NameTextField = new javax.swing.JTextField();
        p3NameTextField = new javax.swing.JTextField();
        p2ScoreTextField = new javax.swing.JTextField();
        p3ScoreTextField = new javax.swing.JTextField();
        firstLabel = new javax.swing.JLabel();
        secLabel = new javax.swing.JLabel();
        thirdLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("TOP 3 PLAYERS");

        p1NameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        p1NameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1NameTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p1NameTextField.setEnabled(false);
        p1NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1NameTextFieldActionPerformed(evt);
            }
        });

        p1ScoreTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        p1ScoreTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1ScoreTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p1ScoreTextField.setEnabled(false);

        playersLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        playersLabel.setText("PLAYERS");

        scoreLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        scoreLabel.setText("SCORES");

        p2NameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        p2NameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2NameTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p2NameTextField.setEnabled(false);

        p3NameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        p3NameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p3NameTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p3NameTextField.setEnabled(false);

        p2ScoreTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        p2ScoreTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2ScoreTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p2ScoreTextField.setEnabled(false);

        p3ScoreTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        p3ScoreTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p3ScoreTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        p3ScoreTextField.setEnabled(false);

        firstLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstLabel.setText("1");

        secLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        secLabel.setText("2");

        thirdLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        thirdLabel.setText("3");

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thirdLabel)
                                    .addComponent(secLabel)
                                    .addComponent(firstLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(p2NameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(p1NameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(p3NameTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(playersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scoreLabel)
                                    .addComponent(p2ScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p1ScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p3ScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playersLabel)
                    .addComponent(scoreLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(p1ScoreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(p1NameTextField))
                    .addComponent(firstLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(secLabel)
                    .addComponent(p2ScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(p3NameTextField)
                        .addComponent(p3ScoreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                    .addComponent(thirdLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Home h = new Home();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
    }//GEN-LAST:event_backButtonActionPerformed

    private void p1NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1NameTextFieldActionPerformed
        
    }//GEN-LAST:event_p1NameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JTextField p1NameTextField;
    private javax.swing.JTextField p1ScoreTextField;
    private javax.swing.JTextField p2NameTextField;
    private javax.swing.JTextField p2ScoreTextField;
    private javax.swing.JTextField p3NameTextField;
    private javax.swing.JTextField p3ScoreTextField;
    private javax.swing.JLabel playersLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel secLabel;
    private javax.swing.JLabel thirdLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
